/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;

import javax.swing.*;



/**
 *
 * @author Thibaut
 */
public class LoginView extends JFrame {

	private TeacherFacade account;
	private MenuView menu;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFrame fLogin; //fenêtre
    private JPanel pLogin, pNorth, pSouth; //panneau
    private JLabel lblLogin; //label Login
    private JLabel lblMdp; //label mot de passe
    private JTextField tfLogin; //champ texte login
    private JTextField tfMdp; //champ texte mot de passe
    private JButton bValid, bCancel;
    // End of variables declaration//GEN-END:variables
	
	/**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

    	//initialisation des widgets
    	fLogin = new JFrame("Authentification");
    	GridLayout glNorth = new GridLayout(2,2);
    	BorderLayout blSouth = new BorderLayout();
    	
    	pLogin = new JPanel();
    	
    	pNorth = new JPanel (glNorth);
    	pSouth = new JPanel (blSouth);
    	
    	//création des widgets
    	pLogin.setSize(getPreferredSize()); //taille du login
    	//getLogin()
    	lblLogin = new JLabel();
    	tfLogin = new JTextField();
    	//getPwd()
    	lblMdp = new JLabel();
    	tfMdp = new JTextField();
        
    	//on ajoute au panneau nord
    	pNorth.add(lblLogin);
    	
    	
    	
        bValid = new JButton("Valider");
        bCancel = new JButton("Annuler");

        

        tfLogin.setText("login");

        tfMdp.setText("mdp");

        lblLogin.setText("Login :");
        lblMdp.setText("Mot de passe : ");
       
        //Panneau Nord
        pLogin.add(lblLogin, glNorth);
        pLogin.add(tfLogin, glNorth);
        pLogin.add(lblMdp, glNorth);
        pLogin.add(tfMdp, glNorth);
        
        
        //Panneau Sud
        pLogin.add(bValid, blSouth.SOUTH);
        pLogin.add(bCancel, blSouth.SOUTH);
        
        fLogin.setSize(450, 450);
        fLogin.add(pLogin);
        
        fLogin.setVisible(true);
        fLogin.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /**
     * Connecte l'utilisateur si son id/pwd est valide
     */
    public void connect() {
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    	new LoginView();
    }

}
