/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;

import javax.swing.*;



/**
 *
 * @author Thibaut
 */
public class LoginView extends JFrame {

	//private TeacherFacade account;
	private MenuView menu;
	
    private JPanel pNorth, pSouth; //panneaux
    private JLabel lblLogin; //label Login
    private JLabel lblMdp; //label mot de passe
    private JTextField tfLogin; //champ texte login
    private JPasswordField tfMdp; //champ texte mot de passe
    private JButton bValid, bCancel;

	
	/**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

    	//initialisation des widgets
    	this.setTitle("Authentification");
    	this.setSize(400,300); //On donne une taille à notre fenêtre
    	
		/** construction du panneau nord */

    	pNorth = new JPanel (); //panneau nord
    	
    	lblLogin = new JLabel("Login :"); //label Login
    	tfLogin = new JTextField();

    	lblMdp = new JLabel("Mot de passe :"); //label mot de passe
    	tfMdp = new JPasswordField();
    	
    	/** ajout des widgets du panneau nord */
    	
    	pNorth.add(lblLogin);
    	pNorth.add(tfLogin);
    	pNorth.add(lblMdp);
    	pNorth.add(tfMdp);
    	
		/** construction du panneau sud */

    	pSouth = new JPanel (); //panneau sud
    	
    	bValid = new JButton("Valider");
    	bCancel = new JButton("Annuler");
    	
    	/** ajout des widgets du panneau sud */
    	
    	pSouth.add(bValid);
    	pSouth.add(bCancel);
    	
    	/** ajout des panneaux à la fenêtre */
    	this.getContentPane().add(pNorth, BorderLayout.NORTH); //On ajoute un panneau au nord
    	this.getContentPane().add(pSouth, BorderLayout.SOUTH); //On ajoute un panneau au sud
    	     
        this.setVisible(true);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        pack();
    }

   
    /**
     * Connecte l'utilisateur si son id/pwd est valide
     */
    public void connect() {
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    	new LoginView();
    }

}
