/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

import BL.TeacherFacade;



/**
 *
 * @author Thibaut
 */
public class LoginView extends JFrame implements ActionListener{

	private TeacherFacade account;
	private MenuView menu;
	
    private JPanel pNorth, pSouth; //panneaux
    private JLabel lblLogin; //label Login
    private JLabel lblMdp; //label mot de passe
    private JTextField tfLogin; //champ texte login
    private JPasswordField tfMdp; //champ texte mot de passe
    private JButton bValid, bCancel;

	
	/**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

    	//initialisation des widgets
    	this.setTitle("Authentification");
    	this.setSize(400,300); //On donne une taille à notre fenêtre
    	this.setResizable(false);
    	
		/** construction du panneau nord */

    	pNorth = new JPanel (new GridLayout(2,2)); //panneau nord
    	//pNorth.setPreferredSize(new Dimension (200,150));
    	
    	lblLogin = new JLabel("Login :"); //label Login
    	tfLogin = new JTextField();
    	tfLogin.setPreferredSize(new Dimension (90, 20));
    	tfLogin.setToolTipText("Enter your login");

    	lblMdp = new JLabel("Mot de passe :"); //label mot de passe
    	tfMdp = new JPasswordField();
    	tfMdp.setPreferredSize(new Dimension (90, 20));
    	tfMdp.setToolTipText("Enter your password");
    	
    	/** ajout des widgets du panneau nord */
    	
    	pNorth.add(lblLogin);
    	pNorth.add(tfLogin);
    	pNorth.add(lblMdp);
    	pNorth.add(tfMdp);
    	
		/** construction du panneau sud */

    	pSouth = new JPanel (); //panneau sud
    	//pSouth.setPreferredSize(new Dimension (200,150));
    	
    	bValid = new JButton("Valider"); bValid.setActionCommand("valid"); bValid.addActionListener(this);
    	bCancel = new JButton("Annuler"); bCancel.setActionCommand("cancel"); bCancel.addActionListener(this);
    	
    	/** ajout des widgets du panneau sud */
    	
    	pSouth.add(bValid);
    	pSouth.add(bCancel);
    	
    	/** ajout des panneaux à la fenêtre */
    	this.getContentPane().add(pNorth, BorderLayout.NORTH); //On ajoute un panneau au nord
    	this.getContentPane().add(pSouth, BorderLayout.SOUTH); //On ajoute un panneau au sud
    	
    	
    	this.setLocationRelativeTo(null);     
        this.setVisible(true);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        pack();
    }

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    	new LoginView();
    }

    /**
     * 
     */

	public void actionPerformed(ActionEvent e) {
			
		if (e.getActionCommand().equals("valid"))
		{
			this.account = new TeacherFacade();
			//System.out.println(this.tfLogin.getText());
			//System.out.println(this.tfMdp.getText());
			boolean connected = this.account.connect(this.tfLogin.getText(), this.tfMdp.getText());
			if (!connected)
			{
				System.out.println("L'utilisateur n'est pas connecté");
			}
			else
			{
				menu = new MenuView(account);
			}
		}
		
		else if (e.getActionCommand().equals("cancel")) 
		{
			System.exit(0);
		}
	}

}
